# -*- coding: utf-8 -*-
"""3_churn_queries.sql

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_uX1Rdg-yKGUn_Jfd5TlRc5Zfbj9mBI
"""

-- Project 3: Churn & Retention (table: telco_customers). churned: 1 = left.

-- 1. Overall churn and retention
SELECT COUNT(*) AS customers, ROUND(AVG(churned)*100,1) AS churn_pct,
       ROUND(100-AVG(churned)*100,1) AS retention_pct FROM telco_customers;

-- 2. Churn by tenure band
SELECT tenure_band, COUNT(*) AS customers, ROUND(AVG(churned)*100,1) AS churn_pct
FROM telco_customers GROUP BY tenure_band ORDER BY churn_pct DESC;

-- 3. Churn by contract type
SELECT contract, ROUND(AVG(churned)*100,1) AS churn_pct
FROM telco_customers GROUP BY contract ORDER BY churn_pct DESC;

-- 4. Churn by customer segment (internet service + senior citizen)
SELECT internetservice, seniorcitizen, COUNT(*) AS customers, ROUND(AVG(churned)*100,1) AS churn_pct
FROM telco_customers GROUP BY internetservice, seniorcitizen ORDER BY churn_pct DESC;

-- 5. Spend: churned vs retained
SELECT churn, ROUND(AVG(monthlycharges),2) AS avg_monthly, ROUND(AVG(totalcharges),2) AS avg_total
FROM telco_customers GROUP BY churn;

-- 6. Revenue at risk: monthly charges lost to churn (subquery)
SELECT ROUND(SUM(monthlycharges),0) AS monthly_revenue_lost,
       ROUND(SUM(monthlycharges)*100.0/(SELECT SUM(monthlycharges) FROM telco_customers),1) AS pct_of_total
FROM telco_customers WHERE churned = 1;