# -*- coding: utf-8 -*-
"""3_churn_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I7QJ7rruhQakrkd6j4wFX8_BWfMnf-XF
"""

"""Project 3: Customer Churn & Retention (dataset: Telco Customer Churn CSV from Kaggle)"""
import os
import pandas as pd
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

os.makedirs("outputs", exist_ok=True)
DB_URL = os.getenv("DB_URL", "sqlite:///portfolio.db")

df = pd.read_csv("data/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.columns = [c.strip().lower() for c in df.columns]
df = df.drop_duplicates()
df["totalcharges"] = pd.to_numeric(df["totalcharges"], errors="coerce")  # blanks in raw file
print("Missing totalcharges:", df["totalcharges"].isna().sum())
df["totalcharges"] = df["totalcharges"].fillna(0)
df["churned"] = (df["churn"] == "Yes").astype(int)
df["tenure_band"] = pd.cut(df["tenure"], [-1, 12, 24, 48, 100], labels=["0-12", "13-24", "25-48", "49+"]).astype(str)
print("Customers:", len(df), "| Churn rate:", f"{df['churned'].mean():.1%}")

by_tenure = (df.groupby("tenure_band")["churned"].mean() * 100).round(1)
by_contract = (df.groupby("contract")["churned"].mean() * 100).round(1)
by_internet = (df.groupby("internetservice")["churned"].mean() * 100).round(1)
print(by_tenure, by_contract, sep="\n")

by_tenure.plot(kind="bar", color="#C00000", title="Churn % by Tenure (months)")
plt.tight_layout(); plt.savefig("outputs/churn_by_tenure.png", dpi=150); plt.clf()
by_contract.plot(kind="bar", color="#2E75B6", title="Churn % by Contract Type")
plt.tight_layout(); plt.savefig("outputs/churn_by_contract.png", dpi=150); plt.clf()
by_internet.plot(kind="bar", color="#548235", title="Churn % by Internet Service")
plt.tight_layout(); plt.savefig("outputs/churn_by_internet.png", dpi=150); plt.clf()
df["churn"].value_counts().plot(kind="pie", autopct="%1.1f%%", title="Retained vs Churned")
plt.ylabel(""); plt.tight_layout(); plt.savefig("outputs/retention_split.png", dpi=150); plt.clf()

df.to_sql("telco_customers", create_engine(DB_URL), if_exists="replace", index=False)
print("Done. Table 'telco_customers' loaded.")